remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
baseurl: "/"
url: "https://alanbesen.github.io/leaderboard.besen.io"

# Build settings
markdown: kramdown
paginate: 5