# Site settings
#baseurl: "/"
#url: "https://alanbesen.github.io/leaderboard.besen.io"

# Theme settings
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# Other settings
paginate: 5