title: IPSC Leaderboard para PractiScore
description: Solução de integração com PractiScore para Leaderboard em tempo real e transmissão online
author: Alan Besen

# Site settings
baseurl: "/"
url: "https://hotsite.scoring.services"
canonical_url: "https://hotsite.scoring.services"

# SEO settings
lang: pt-BR
twitter:
  username: scoring_services
  card: summary_large_image
social:
  name: Scoring Services
  links:
    - https://scoring.services
    - https://hotsite.scoring.services

# Build settings
markdown: kramdown
paginate: 5

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap settings
sitemap:
  filename: sitemap.xml
  exclude:
    - "/404.html"
    - "/assets/**"
  include_posts:
    - "/index.html"
  change_frequency_name: "weekly"
  priority_name: "0.8"